// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/facebook.js"
    | "/icon/icon-128.png"
    | "/icon/icon-16.png"
    | "/icon/icon-32.png"
    | "/icon/icon-48.png"
    | "/icon/icon.svg"
    | "/options.html"
    | "/popup.html"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
